# -*- coding: utf-8 -*-
"""Final Exam Review 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxevn5Md32z3bBlDL6TRmgfJwzHfWyQ1
"""

#Lucas Vandenakker
#CS-175
#Q1

#The function will return
#10
#15

#Just checking my answers
def multiply_func(a,b=2):
  return a*b

print( multiply_func(5))

print( multiply_func(5,3))

#Yes, my answers are correct

#Lucas Vandenakker
#CS-175
#Q2

x = [1,2,4,5,6,7,8,10]

#Creates a new list of values if the index of the value is even
newList = [i for i in x if x.index(i) % 2 == 0]

print(newList)

#Other way

print(x[::2])

#Lucas Vandenakker
#CS-175
#Q3
#it will print the list [6,7,8], is not inclusive

c = [1,2,3,4,5,6,7,8,9]

f=c[-4:-1]

print(f)

#Lucas Vandenakker
#CS-175
#Q4

nested = [[1,2,3], [4,5,6], [7,8,9]]

print(f"{nested[1][1]} and {nested[1][2]}")

print(nested[1][-2:])

#Lucas Vandenakker
#CS-175
#Q5

nested_list = [[1,2,3],[4,5,6],[7,8,9]]

for i in range(len(nested_list)):
  nested_list[i] = nested_list[i][::-1]

print(f"Each reversed row: {nested_list}")

print(f"Reversed list: {nested_list[::-1]}")

#Lucas Vandenakker
#CS-175
#Q6
words = ["Deep", "fried", "wings"]
word= "-".join(words)

print(word)

#Lucas Vandenakker
#CS-175
#Q7

text = "The beach is beautiful, and spending time at beach is always enjoyable!"

substring = "beach"

limited_text = text[:30]

# Find the last occurrence of the substring within the first 30 characters
index = limited_text.rfind(substring)

print(index)

print("The actual index of beach is: " , text.rfind(substring))

#Lucas Vandenakker
#CS-175
#Q8

number_str = "00012345"

str1 = number_str.lstrip("0")

print(str1)

#Lucas Vandenakker
#CS-175
#Q9
text = ["Line1", "Line2", "Line3"]
for word in text:
  print(word)

#Lucas Vandenakker
#CS-175
#Q10

userweight = int(input("Please enter your weight: "))
userheight = float(input("Please enter your height: "))

bmi = userweight/pow(userheight, 2)

if bmi >= 25:
  print("You are overweight")
else:
    print("You are normal weight")