# -*- coding: utf-8 -*-
"""FinalExamReviewTrueOrFalse

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWG46QjQg7njgfUgNkRS4qXWv9Fhv_Ox
"""

#Lucas Vandenakker
#CS-175
#Q1

#False, CPUs are small

#Lucas Vandenakker
#CS-175
#Q2

#True, Memory is known as RAM

#Lucas Vandenakker
#CS-175
#Q3

#True

#Lucas Vandenakker
#CS-175
#Q4

#False

#Lucas Vandenakker
#CS-175
#Q5

#True

#Lucas Vandenakker
#CS-175
#Q6

#False, it is a low level language

#Lucas Vandenakker
#CS-175
#Q7

#True

#Lucas Vandenakker
#CS-175
#Q8

#False

#Lucas Vandenakker
#CS-175
#Q9

#False

#Lucas Vandenakker
#CS-175
#Q10

#False

#Lucas Vandenakker
#CS-175
#Q11

#True

#Lucas Vandenakker
#CS-175
#Q12

#False

#Lucas Vandenakker
#CS-175
#Q13

#False

#Lucas Vandenakker
#CS-175
#Q14

#False

#Lucas Vandenakker
#CS-175
#Q15

#True

#Lucas Vandenakker
#CS-175
#Q16

#False

#Lucas Vandenakker
#CS-175
#Q17

#True

#Lucas Vandenakker
#CS-175
#Q18

#True

#Lucas Vandenakker
#CS-175
#Q18

#True

#Lucas Vandenakker
#CS-175
#Short Answer 1

nums = [1,3,7,3,8]


print(sum(nums))

#Lucas Vandenakker
#CS-175
#Short Answer 2

#output is 1,2,3,4. This is because x and y reference the same object in memory so if one is changed, the other one is as well
x = [1, 2, 3]
y = x
y.append(4)
print(x)

#Lucas Vandenakker
#CS-175
#Short Answer 3

palindrome = "Race car"

reversed = palindrome[::-1]

noSpaceP= palindrome.replace(" ", "")

reversed = reversed.replace(" ", "")


if(noSpaceP.lower() == reversed.lower()):
  print("This word is a palindrome")

else:
  print("This is not a palindrome")

#Lucas Vandenakker
#CS-175
#Short Answer 4

#prints 6,1 / 5, 6 / 4, 30 / 3, 120 / 2,360 / 1, 720 so prints 720

def Recur_factor(n, a=1):
  if(n == 0):
    return a

  return Recur_factor(n-1, n*a)

print(Recur_factor(6))

#Lucas Vandenakker
#CS-175
#Short Answer 5
import csv
#5
#2
#Error Message e

def demonstate_division(file_name):
  try:
    with open(file_name, 'r') as file:
      reader = csv.reader(file)
      for row in reader:
        try:
          result = int(row[0])/int(row[1])
          print(f"Result of division: {result}")
        except Exception as e:
          print(f"{e}")
  except FileNotFoundError:
    print(f"Error: The file {file_name} does not exist")

demonstate_division("data.csv")

#Lucas Vandenakker
#CS-175
#Short Answer 6

quiz = {
    ("What is the capital of Italy?", "Rome"),
    ("What is 50 + 250?", "300"),
    ("What is the largest planet in our solar system?", "Jupiter"),
    ("What wrote 'A thousand splendid sun'?", "Khaled Hosseini"),
    ("What is the chemical symbol for water?", "H2O"),
}

num_correct = 0

for question, ans in quiz:
  user_answer = input(f"Question: " + question)
  if(user_answer == ans):
    num_correct+=1
    print("correct")
  else:
    print("Incorrect")


print(f"You got {num_correct} correct out of 5 questions")

#Lucas Vandenakker
#CS-175
#Short Answer 7

sample_list = [1,2,2,3,4,4,5,6,6,7,8,8,9,10,10]

unique_list = set(sample_list)

print(f"Unique List: {unique_list}")

#Lucas Vandenakker
#CS-175
#Short Answer 8

f1 = int(input("Enter an integer: "))
f2 = int(input("Enter an integer: "))

print(f'    Mathematical operations')

print(f"{'Sum:':<20}{f1 + f2:>10.2f}")
print(f"{'Difference:':<20}{f1 - f2:>10.2f}")
print(f"{'Product:':<20}{f1 * f2:>10.2f}")
print(f"{'Integer Division:':<20}{f1 / f2:>10.2f}")
print(f"{'Average:':<20}{(f1 + f2) / 2:>10.2f}")
print(f"{'Remainder:':<20}{f1 % f2:>10.2f}")